### ISSUE TITLE
Failing to send data after second APPEND command

### ISSUE THREAD

**Issue by qskousen** [emersion/go-imap#113]
I am working on an internal email migration tool, and I am using go-imap to copy email from one server to another. However, I have hit a bug where the server (running Postfix) responds with `+ OK` to a command and then the program hangs.

Here is the sequence of events. I try to `APPEND` a message to the new server:

    yaWmXw APPEND INBOX (\Seen \receiptchecked \Answered) " 5-Oct-2015 22:33:11 +0000" {37020}

The new server doesn't understand the `\receiptchecked` flag so it objects:

    yaWmXw BAD Error in IMAP command APPEND: Invalid system flag \RECEIPTCHECKED (0.000 + 0.000 secs).

I remove the offending flag and try again:

    uoTzlA APPEND INBOX (\Seen \Answered) " 5-Oct-2015 22:33:11 +0000" {37020}

And then the server responds with the `+ OK` indicating it is ready for the data, but go-imap never sends it.

Here is a snippet of the code that is doing the above:

```go
err = c.Append(target, msg.Flags, date, msg.GetBody("BODY[]"))
if err != nil {
	if strings.Contains(err.Error(),"Invalid system flag") {
		// splits the offending flag out of the error string
		violator := strings.Split(strings.Split(err.Error(), "\\")[1]," ")[0]
		tmp := []string{}
		for k, v := range msg.Flags {
			if strings.Contains(strings.ToUpper(v), violator) {
				tmp = remove(msg.Flags, k)
			}
		}
		err = c.Append(target, tmp, date, msg.GetBody("BODY[]"))
		if err != nil {
			log.Println(err.Error())
		}
	} else {
		log.Println(err.Error())
	}
}
```

I did a <kbd>CTRL</kbd> + <kbd>\\</kbd> while the program was hung, here is the lengthy output from that:

```
^\SIGQUIT: quit
PC=0x457473 m=0 sigcode=128

goroutine 38 [syscall]:
runtime.notetsleepg(0xcfb778, 0x115df29482, 0x0)
        /usr/lib/go-1.8/src/runtime/lock_futex.go:205 +0x42 fp=0xc4201a6f60 sp=0xc4201a6f30
runtime.timerproc()
        /usr/lib/go-1.8/src/runtime/time.go:209 +0x327 fp=0xc4201a6fe0 sp=0xc4201a6f60
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4201a6fe8 sp=0xc4201a6fe0
created by runtime.addtimerLocked
        /usr/lib/go-1.8/src/runtime/time.go:116 +0xed

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fa5edd33fc0, 0x72, 0x0)
        /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42015e848, 0x72, 0x0, 0xc420180840)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42015e848, 0xffffffffffffffff, 0x0)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42015e7e0, 0x0, 0xc43740, 0xc420180840)
        /usr/lib/go-1.8/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000e388, 0xc4201b2260, 0x9082c0, 0xffffffffffffffff)
        /usr/lib/go-1.8/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000e388, 0xc420143d98, 0xc420143da0, 0xc420143d90)
        /usr/lib/go-1.8/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42000e388, 0xa1ae68, 0xc4201b21e0, 0xc48e00, 0xc4201636b0)
        /usr/lib/go-1.8/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc420020dc0, 0xc48780, 0xc42000e388, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc420020dc0, 0xc420020dc0, 0xc420178500)
        /usr/lib/go-1.8/src/net/http/server.go:2585 +0xb0
net/http.ListenAndServe(0x9a6f37, 0x5, 0xc44440, 0xc420178500, 0x1, 0xc4201340f0)
        /usr/lib/go-1.8/src/net/http/server.go:2787 +0x7f
main.main()
        /mnt/data/go/src/gl.syf.me/qt/mbs-email-migrate/main.go:41 +0x242

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc420128500)
        /usr/lib/go-1.8/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
        /usr/lib/go-1.8/src/database/sql/sql.go:582 +0x212

goroutine 30 [select]:
net/http.(*persistConn).writeLoop(0xc4201b4ea0)
        /usr/lib/go-1.8/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.8/src/net/http/transport.go:1118 +0xa5a

goroutine 25 [IO wait]:
net.runtime_pollWait(0x7fa5edd33f00, 0x72, 0x5)
        /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42015e8b8, 0x72, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42015e8b8, 0xc42017e000, 0x1000)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc42015e850, 0xc42017e000, 0x1000, 0x1000, 0x0, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e390, 0xc42017e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc42017c000, 0xc42017e000, 0x1000, 0x1000, 0xc42013f928, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42001cf00)
        /usr/lib/go-1.8/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc42001cf00, 0xc42017870a, 0xc420145f00, 0x0, 0xc42013fa98, 0x625c09, 0xc42000e398)
        /usr/lib/go-1.8/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc42001cf00, 0xc420168900, 0x100, 0xf8, 0x997040, 0x0, 0x4693f2)
        /usr/lib/go-1.8/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc4201637a0, 0xc42013fac8, 0xc42013fac8, 0x410cc8, 0x100, 0x997040)
        /usr/lib/go-1.8/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc4201637a0, 0xc420168900, 0x72, 0x8000000000000000, 0x0)
        /usr/lib/go-1.8/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc42001cf00, 0x0, 0xc420168900, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc420128780, 0xc48d40, 0xc420145fc0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc420128780, 0xc48d40, 0xc420145fc0)
        /usr/lib/go-1.8/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
        /usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce

goroutine 37 [select]:
github.com/emersion/go-imap/client.(*Client).execute(0xc4204bf180, 0xc41b80, 0xc420492370, 0x0, 0x0, 0xc420078680, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:165 +0x63b
github.com/emersion/go-imap/client.(*Client).Append(0xc4204bf180, 0x9a717b, 0x5, 0xc420488a50, 0x2, 0x3, 0xecda4f1a7, 0xc400000000, 0xc42001d560, 0xc453c0, ...)
        /mnt/data/go/src/github.com/emersion/go-imap/client/cmd_auth.go:229 +0x13b
gl.syf.me/qt/mbs-email-migrate/controllers.(*status).migrateTask(0xc420189050, 0xc4201285a0)
        /mnt/data/go/src/gl.syf.me/qt/mbs-email-migrate/controllers/websocket.go:261 +0x1db7
created by gl.syf.me/qt/mbs-email-migrate/controllers.WebSocket.func1
        /mnt/data/go/src/gl.syf.me/qt/mbs-email-migrate/controllers/websocket.go:88 +0x815

goroutine 59 [chan receive]:
github.com/emersion/go-imap.(*MultiRespHandler).HandleFrom(0xc420489860, 0xc42001c7e0, 0xc4204ea190, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/handle.go:65 +0x54
created by github.com/emersion/go-imap/client.New
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:448 +0x3bc

goroutine 78 [chan receive]:
github.com/emersion/go-imap.(*Writer).writeLiteral(0xc4204e0c80, 0xc453c0, 0xc4200608c0, 0xc453c0, 0xc4200608c0)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:146 +0x196
github.com/emersion/go-imap.(*Writer).writeField(0xc4204e0c80, 0x98fba0, 0xc4200608c0, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:170 +0x66a
github.com/emersion/go-imap.(*Writer).writeFields(0xc4204e0c80, 0xc42001d680, 0x6, 0x6, 0xc420352690, 0xc4204d6720)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:109 +0x6e
github.com/emersion/go-imap.(*Writer).writeLine(0xc4204e0c80, 0xc42001d680, 0x6, 0x6, 0xc420352600, 0x4)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:209 +0x4d
github.com/emersion/go-imap.(*Command).WriteTo(0xc420352680, 0xc4204e0c80, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/command.go:69 +0x1d0
github.com/emersion/go-imap/client.(*Client).execute.func1(0xc42001d620, 0xc420352680, 0xc4204bf180)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:149 +0x3c
created by github.com/emersion/go-imap/client.(*Client).execute
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:150 +0x1d9

goroutine 29 [IO wait]:
net.runtime_pollWait(0x7fa5edd33cc0, 0x72, 0x8)
        /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420196848, 0x72, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420196848, 0xc4204a4000, 0x4000)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4201967e0, 0xc4204a4000, 0x4000, 0x4000, 0x0, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc420314160, 0xc4204a4000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc420189f80, 0x7fa5edd341a0, 0xc420314160, 0x5, 0xc420314160, 0xc420046870)
        /usr/lib/go-1.8/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc4201b8380, 0xa1b417, 0xc4201b84a0, 0x452260)
        /usr/lib/go-1.8/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc4201b8380, 0xc420329000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.8/src/crypto/tls/conn.go:1134 +0x11d
net/http.(*persistConn).Read(0xc4201b4ea0, 0xc420329000, 0x1000, 0x1000, 0x5, 0x450530, 0xc42001c2a0)
        /usr/lib/go-1.8/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc420194060)
        /usr/lib/go-1.8/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc420194060, 0x1, 0xc420046be5, 0x1, 0x0, 0xc420194120, 0x0)
        /usr/lib/go-1.8/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc4201b4ea0)
        /usr/lib/go-1.8/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
        /usr/lib/go-1.8/src/net/http/transport.go:1117 +0xa35

goroutine 57 [chan receive]:
github.com/emersion/go-imap/client.(*Client).handleContinuationReqs(0xc4204bedc0, 0xc42001c720)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:228 +0xea
created by github.com/emersion/go-imap/client.New
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:446 +0x36b

goroutine 58 [chan receive]:
github.com/emersion/go-imap/client.(*Client).handleUnilateral(0xc4204bedc0)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:263 +0x146
created by github.com/emersion/go-imap/client.New
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:447 +0x38d

goroutine 60 [IO wait]:
net.runtime_pollWait(0x7fa5edd33b40, 0x72, 0x9)
        /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420196298, 0x72, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420196298, 0xc4204ed000, 0x1000)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420196230, 0xc4204ed000, 0x1000, 0x1000, 0x0, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e048, 0xc4204ed000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/net.go:181 +0x70
io.(*teeReader).Read(0xc4204e0b00, 0xc4204ed000, 0x1000, 0x1000, 0xc4204f0800, 0x10, 0x10)
        /usr/lib/go-1.8/src/io/io.go:523 +0x55
bufio.(*Reader).fill(0xc42001c780)
        /usr/lib/go-1.8/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadRune(0xc42001c780, 0xf, 0xc420041de0, 0x7fd8b2, 0xc42001c780)
        /usr/lib/go-1.8/src/bufio/bufio.go:270 +0xb7
github.com/emersion/go-imap.(*Reader).ReadAtom(0xc420489830, 0xa1b3c8, 0xc42032d400, 0x9ae9aa, 0xc)
        /mnt/data/go/src/github.com/emersion/go-imap/read.go:154 +0x5f
github.com/emersion/go-imap.ReadResp(0xc420489830, 0xc42001ca80, 0x0, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/response.go:64 +0x43
github.com/emersion/go-imap/client.(*Client).read(0xc4204bedc0, 0xc42001ca80, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:98 +0xc1
created by github.com/emersion/go-imap/client.(*Client).handleUnilateral
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:261 +0x100

goroutine 62 [chan receive]:
github.com/emersion/go-imap/client.(*Client).handleContinuationReqs(0xc4204bf180, 0xc42001d020)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:228 +0xea
created by github.com/emersion/go-imap/client.New
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:446 +0x36b

goroutine 63 [chan receive]:
github.com/emersion/go-imap/client.(*Client).handleUnilateral(0xc4204bf180)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:263 +0x146
created by github.com/emersion/go-imap/client.New
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:447 +0x38d

goroutine 64 [chan receive]:
github.com/emersion/go-imap.(*MultiRespHandler).HandleFrom(0xc420489a40, 0xc42001d140, 0xc4204ea280, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/handle.go:65 +0x54
created by github.com/emersion/go-imap/client.New
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:448 +0x3bc

goroutine 65 [IO wait]:
net.runtime_pollWait(0x7fa5edd33c00, 0x72, 0xa)
        /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420060148, 0x72, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420060148, 0xc42032dc00, 0x400)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4200600e0, 0xc42032dc00, 0x400, 0x400, 0x0, 0xc44dc0, 0xc3f5f8)
        /usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e060, 0xc42032dc00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc420489aa0, 0x7fa5edd341a0, 0xc42000e060, 0x5, 0xc42000e060, 0x0)
        /usr/lib/go-1.8/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc4204b0000, 0xa1b417, 0xc4204b0120, 0x10)
        /usr/lib/go-1.8/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc4204b0000, 0xc4204c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.8/src/crypto/tls/conn.go:1134 +0x11d
io.(*teeReader).Read(0xc4204d31e0, 0xc4204c7000, 0x1000, 0x1000, 0xc4204f0a00, 0x3, 0x3)
        /usr/lib/go-1.8/src/io/io.go:523 +0x55
bufio.(*Reader).fill(0xc42001d080)
        /usr/lib/go-1.8/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadRune(0xc42001d080, 0x2, 0xc420040de0, 0x7fd8b2, 0xc42001d080)
        /usr/lib/go-1.8/src/bufio/bufio.go:270 +0xb7
github.com/emersion/go-imap.(*Reader).ReadAtom(0xc420489a10, 0xa1b3c8, 0xc42006a000, 0x9ae9aa, 0xc)
        /mnt/data/go/src/github.com/emersion/go-imap/read.go:154 +0x5f
github.com/emersion/go-imap.ReadResp(0xc420489a10, 0xc42001d320, 0x0, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/response.go:64 +0x43
github.com/emersion/go-imap/client.(*Client).read(0xc4204bf180, 0xc42001d320, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:98 +0xc1
created by github.com/emersion/go-imap/client.(*Client).handleUnilateral
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:261 +0x100

goroutine 99 [chan receive]:
github.com/emersion/go-imap.(*Writer).writeLiteral(0xc4204e0c80, 0xc453c0, 0xc4200608c0, 0xc453c0, 0xc4200608c0)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:146 +0x196
github.com/emersion/go-imap.(*Writer).writeField(0xc4204e0c80, 0x98fba0, 0xc4200608c0, 0x0, 0x0)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:170 +0x66a
github.com/emersion/go-imap.(*Writer).writeFields(0xc4204e0c80, 0xc420316120, 0x6, 0x6, 0xc420401910, 0xc4204f0a20)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:109 +0x6e
github.com/emersion/go-imap.(*Writer).writeLine(0xc4204e0c80, 0xc420316120, 0x6, 0x6, 0xc4204018c0, 0x4)
        /mnt/data/go/src/github.com/emersion/go-imap/write.go:209 +0x4d
github.com/emersion/go-imap.(*Command).WriteTo(0xc420401900, 0xc4204e0c80, 0xa1b5f8, 0xc420035fc8)
        /mnt/data/go/src/github.com/emersion/go-imap/command.go:69 +0x1d0
github.com/emersion/go-imap/client.(*Client).execute.func1(0xc4203160c0, 0xc420401900, 0xc4204bf180)
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:149 +0x3c
created by github.com/emersion/go-imap/client.(*Client).execute
        /mnt/data/go/src/github.com/emersion/go-imap/client/client.go:150 +0x1d9

rax    0xfffffffffffffffc
rbx    0x23343082
rcx    0x457473
rdx    0x0
rdi    0xcfb778
rsi    0x0
rbp    0xc4201a6ee8
rsp    0xc4201a6ea0
r8     0x0
r9     0x0
r10    0xc4201a6ed8
r11    0x206
r12    0x1
r13    0x111
r14    0x1100
r15    0x200
rip    0x457473
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
exit status 2
```

**Comment by qskousen** [comment]
The lines at the top of the report are from the debug log, e.g.

```yaWmXw APPEND INBOX (\Seen \receiptchecked \Answered) " 5-Oct-2015 22:33:11 +0000" {37020}```

**Comment by emersion** [comment]
All right. Does adding a `time.Sleep()` just before running the second command "solves" the issue? It's just to check if it's a data race.
