### ISSUE TITLE
Panic when executing client.Authenticate with Xaouth2

### ISSUE THREAD

**Issue by MrDHat** [emersion/go-imap#148]
This is what my code looks like:

```golang
saslClient := sasl.NewXoauth2Client(s.EmailID, s.OauthToken)
log.Println(saslClient)
err := s.ImapClient.Authenticate(saslClient)
log.Println(err)
```

The second line prints: 
```
&{xxxxx@xxxxxx.com <oauth-token>}
```

When I add the Authenticate line, the code panics. I am not sure what I am doing wrong here. I am running this against the gmail server.

FWIW, the `s` obj is a custom struct which has the following values
```golang
&{xxxxx@xxxxxx.com  google imap.gmail.com:993 <oauth-token><nil>}
```

Not sure if its related, but I also get a panic on:
```golang
ok, err := s.ImapClient.SupportAuth(sasl.Xoauth2)
log.Println(ok, err)
```

**Comment by emersion** [comment]
Can you post the panic stack trace?

**Comment by MrDHat** [comment]
Here is the stack track for panic caused by `SupportAuth`
```golang
ok, err := s.ImapClient.SupportAuth(sasl.Xoauth2)
	log.Println(ok, err)
```

```
goroutine 21 [running]:
panic(0x6c0ca0, 0x8896f0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client.(*Client).Support(0x0, 0xc42004f5e0, 0xc, 0x70cd61, 0x7, 0xc42004f5e0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client/cmd_any.go:38 +0x26
github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client.(*Client).SupportAuth(0x0, 0x70cd61, 0x7, 0xc4200ba2c0, 0x52, 0x4a)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client/cmd_noauth.go:69 +0x7a
github.com/getstrike/imap-sync-block/app/imapprovider.(*Sync).OauthLogin(0xc420060780, 0xc400000008)
	github.com/getstrike/imap-sync-block/app/imapprovider/_test/_obj_test/imapprovider.go:58 +0x13f
github.com/getstrike/imap-sync-block/app/imapprovider.TestOauthLogin.func1.1()
	/go/src/github.com/getstrike/imap-sync-block/app/imapprovider/imapprovider_test.go:38 +0x2a
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:97 +0x463
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.EnsureGoroutineId(0xc42006ae10)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/gid.go:19 +0x112
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues(0xc420042860, 0xc42006ad80, 0xc4203dc120)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:63 +0x177
github.com/getstrike/imap-sync-block/app/imapprovider.TestOauthLogin.func1()
	/go/src/github.com/getstrike/imap-sync-block/app/imapprovider/imapprovider_test.go:37 +0x265
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:97 +0x463
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.EnsureGoroutineId.func1()
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/gid.go:24 +0x31
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls._m(0x0, 0xc4203dc100)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/stack_tags.go:74 +0x31
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc4203dc100)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/stack_tags.go:54 +0x35
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.addStackTag(0x0, 0xc4203dc100)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/stack_tags.go:49 +0x3a
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.EnsureGoroutineId(0xc42006ab40)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/gid.go:24 +0xc9
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues(0xc420042860, 0xc42006aae0, 0xc4203dc0c0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:63 +0x177
github.com/getstrike/imap-sync-block/app/imapprovider.TestOauthLogin(0xc4200a81e0)
	/go/src/github.com/getstrike/imap-sync-block/app/imapprovider/imapprovider_test.go:29 +0xa6
testing.tRunner(0xc4200a81e0, 0x71c6a0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200a8000, 0x70e8f4, 0xe, 0x71c6a0, 0x47bd01)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200a8000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200a8000, 0xc420051d78)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42000c200, 0x88eee0, 0x7, 0x7, 0x160)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420051f18, 0x24)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	github.com/getstrike/imap-sync-block/app/imapprovider/_test/_testmain.go:102 +0x1b2
```


Here it is for `Authenticate`

```golang
saslClient := sasl.NewXoauth2Client(s.EmailID, s.OauthToken)
	log.Println(s)
	log.Println(saslClient)
	err := s.ImapClient.Authenticate(saslClient)
	log.Println(err)
```
```
goroutine 21 [running]:
panic(0x6c0ca0, 0x8896f0)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client.(*Client).State(0x0, 0x0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client/client.go:245 +0x22
github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client.(*Client).Authenticate(0x0, 0x873380, 0xc4201103e0, 0xc420042bc0, 0xc42006b230)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/emersion/go-imap/client/cmd_noauth.go:76 +0x40
github.com/getstrike/imap-sync-block/app/imapprovider.(*Sync).OauthLogin(0xc420388420, 0xc400000008)
	github.com/getstrike/imap-sync-block/app/imapprovider/_test/_obj_test/imapprovider.go:62 +0x27a
github.com/getstrike/imap-sync-block/app/imapprovider.TestOauthLogin.func1.1()
	/go/src/github.com/getstrike/imap-sync-block/app/imapprovider/imapprovider_test.go:38 +0x2a
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:97 +0x463
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.EnsureGoroutineId(0xc42006b200)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/gid.go:19 +0x112
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues(0xc420042860, 0xc42006b1a0, 0xc420110380)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:63 +0x177
github.com/getstrike/imap-sync-block/app/imapprovider.TestOauthLogin.func1()
	/go/src/github.com/getstrike/imap-sync-block/app/imapprovider/imapprovider_test.go:37 +0x265
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:97 +0x463
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.EnsureGoroutineId.func1()
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/gid.go:24 +0x31
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls._m(0x0, 0xc420110360)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/stack_tags.go:74 +0x31
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc420110360)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/stack_tags.go:54 +0x35
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.addStackTag(0x0, 0xc420110360)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/stack_tags.go:49 +0x3a
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.EnsureGoroutineId(0xc42006b0b0)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/gid.go:24 +0xc9
github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls.(*ContextManager).SetValues(0xc420042860, 0xc42006b050, 0xc420110320)
	/go/src/github.com/getstrike/imap-sync-block/app/vendor/github.com/jtolds/gls/context.go:63 +0x177
github.com/getstrike/imap-sync-block/app/imapprovider.TestOauthLogin(0xc4200a81e0)
	/go/src/github.com/getstrike/imap-sync-block/app/imapprovider/imapprovider_test.go:29 +0xa6
testing.tRunner(0xc4200a81e0, 0x71c6a0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200a8000, 0x70e8f4, 0xe, 0x71c6a0, 0x47bd01)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200a8000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200a8000, 0xc420051d78)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42000c200, 0x88eee0, 0x7, 0x7, 0x160)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420051f18, 0x24)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	github.com/getstrike/imap-sync-block/app/imapprovider/_test/_testmain.go:102 +0x1b2

```

**Comment by emersion** [comment]
These errors make no sense. Are you sure `s.ImapClient` is not `nil`? Try to print it.

**Comment by MrDHat** [comment]
Ah yes.. It turns out my initializer had a bug which did not connect to the IMAP server before attempting to authenticate.
Sorry, my mistake. Thanks for the amazing package(s) btw 🥇
