### ISSUE TITLE
APPEND test fails in rare cases

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#29]
It timeouts.

Example: https://travis-ci.org/emersion/go-imap/builds/146058423

**Comment by emersion** [comment]
```
SIGQUIT: quit

PC=0x460911 m=0

goroutine 0 [idle]:

runtime.futex(0x8f2508, 0x0, 0x0, 0x0, 0x0, 0x8f1d10, 0x0, 0x0, 0x40fd74, 0x8f2508, ...)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/sys_linux_amd64.s:302 +0x21

runtime.futexsleep(0x8f2508, 0x0, 0xffffffffffffffff)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/os1_linux.go:40 +0x53

runtime.notesleep(0x8f2508)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/lock_futex.go:145 +0xa4

runtime.stopm()

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1535 +0x10b

runtime.findrunnable(0xc820020000, 0x0)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1973 +0x739

runtime.schedule()

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:2072 +0x24f

runtime.park_m(0xc8200a8480)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:2137 +0x18b

runtime.mcall(0x7fff72fc30b0)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive]:

testing.RunTests(0x7e58a0, 0x8ef4e0, 0x21, 0x21, 0xc82007ca01)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:583 +0x8d2

testing.(*M).Run(0xc82004def8, 0x8f1a00)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:515 +0x81

main.main()

	github.com/emersion/go-imap/client/_test/_testmain.go:176 +0x253

goroutine 17 [syscall, locked to thread]:

runtime.goexit()

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1

goroutine 27 [IO wait]:

net.runtime_pollWait(0x7f760a391cf8, 0x72, 0xc8200db500)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/netpoll.go:160 +0x60

net.(*pollDesc).Wait(0xc820059410, 0x72, 0x0, 0x0)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:73 +0x3a

net.(*pollDesc).WaitRead(0xc820059410, 0x0, 0x0)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_poll_runtime.go:78 +0x36

net.(*netFD).Read(0xc8200593b0, 0xc8200db500, 0x1e, 0x1e, 0x0, 0x7f760a38d050, 0xc8200180b8)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/fd_unix.go:250 +0x23a

net.(*conn).Read(0xc82002c260, 0xc8200db500, 0x1e, 0x1e, 0x0, 0x0, 0x0)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/net/net.go:172 +0xe4

io.ReadAtLeast(0x7f760a392980, 0xc82002c260, 0xc8200db500, 0x1e, 0x1e, 0x1e, 0x0, 0x0, 0x0)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/io/io.go:297 +0xe6

io.ReadFull(0x7f760a392980, 0xc82002c260, 0xc8200db500, 0x1e, 0x1e, 0x1e, 0x0, 0x0)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/io/io.go:315 +0x62

github.com/emersion/go-imap/client_test.TestClient_Append.func2(0x7f760a392920, 0xc82002c260)

	/home/travis/gopath/src/github.com/emersion/go-imap/client/cmd_auth_test.go:362 +0x2e4

github.com/emersion/go-imap/client_test.testClient(0xc8200b6120, 0xc82009a860, 0xc82003df40)

	/home/travis/gopath/src/github.com/emersion/go-imap/client/client_test.go:56 +0x479

github.com/emersion/go-imap/client_test.TestClient_Append(0xc8200b6120)

	/home/travis/gopath/src/github.com/emersion/go-imap/client/cmd_auth_test.go:373 +0xc6

testing.tRunner(0xc8200b6120, 0x8ef648)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:473 +0x98

created by testing.RunTests

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/testing/testing.go:582 +0x892

goroutine 28 [chan receive]:

github.com/emersion/go-imap.(*Writer).writeLiteral(0xc82009a940, 0x7f760a34d0a8, 0xc82009c3f0, 0x0, 0x0)

	/home/travis/gopath/src/github.com/emersion/go-imap/write.go:155 +0x251

github.com/emersion/go-imap.(*Writer).writeField(0xc82009a940, 0x74b340, 0xc82009c3f0, 0x0, 0x0)

	/home/travis/gopath/src/github.com/emersion/go-imap/write.go:179 +0x29b

github.com/emersion/go-imap.(*Writer).writeFields(0xc82009a940, 0xc8200af320, 0x6, 0x6, 0x0, 0x0)

	/home/travis/gopath/src/github.com/emersion/go-imap/write.go:109 +0x12b

github.com/emersion/go-imap.(*Writer).writeLine(0xc82009a940, 0xc8200af320, 0x6, 0x6, 0x0, 0x0)

	/home/travis/gopath/src/github.com/emersion/go-imap/write.go:216 +0x4f

github.com/emersion/go-imap.(*Command).WriteTo(0xc8200a4580, 0xc82009a940, 0x0, 0x0)

	/home/travis/gopath/src/github.com/emersion/go-imap/command.go:69 +0x30b

github.com/emersion/go-imap/client.(*Client).execute(0xc8200b2280, 0x7f760a34d0d8, 0xc8200b81e0, 0x0, 0x0, 0x0, 0x0, 0x0)

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:188 +0x16f

github.com/emersion/go-imap/client.(*Client).Append(0xc8200b2280, 0x75e8c8, 0x5, 0xc82009a9e0, 0x2, 0x2, 0xec28be770, 0x0, 0x8ee040, 0x7f760a34d0a8, ...)

	github.com/emersion/go-imap/client/_test/_obj_test/cmd_auth.go:312 +0x1e8

github.com/emersion/go-imap/client_test.TestClient_Append.func1(0xc8200b2280, 0x0, 0x0)

	/home/travis/gopath/src/github.com/emersion/go-imap/client/cmd_auth_test.go:347 +0x295

github.com/emersion/go-imap/client_test.testClient.func1(0x7f760a391890, 0xc8200a2058, 0xc8200aef60, 0xc82009a860)

	/home/travis/gopath/src/github.com/emersion/go-imap/client/client_test.go:35 +0xf0

created by github.com/emersion/go-imap/client_test.testClient

	/home/travis/gopath/src/github.com/emersion/go-imap/client/client_test.go:44 +0x1ef

goroutine 32 [chan receive]:

github.com/emersion/go-imap.(*Writer).writeLiteral.func1(0xc82009c460, 0xc82009a940)

	/home/travis/gopath/src/github.com/emersion/go-imap/write.go:139 +0x40

created by github.com/emersion/go-imap.(*Writer).writeLiteral

	/home/travis/gopath/src/github.com/emersion/go-imap/write.go:140 +0xe8

goroutine 30 [chan receive]:

github.com/emersion/go-imap/client.(*Client).handleUnilateral(0xc8200b2280)

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:309 +0x149

created by github.com/emersion/go-imap/client.New

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:509 +0x42d

goroutine 29 [semacquire]:

sync.runtime_Semacquire(0xc8200b0afc)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/sema.go:47 +0x26

sync.(*Mutex).Lock(0xc8200b0af8)

	/home/travis/.gimme/versions/go1.6.linux.amd64/src/sync/mutex.go:83 +0x1c4

github.com/emersion/go-imap/client.(*Client).addHandler(0xc8200b2280, 0xc8200f8120)

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:158 +0x5e

github.com/emersion/go-imap/client.(*Client).handleContinuationReqs(0xc8200b2280, 0xc8200aefc0)

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:264 +0x6c

created by github.com/emersion/go-imap/client.New

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:508 +0x408

goroutine 31 [chan send]:

github.com/emersion/go-imap/client.(*Client).read(0xc8200b2280, 0xc8200af1a0, 0x0, 0x0)

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:134 +0x8ef

created by github.com/emersion/go-imap/client.(*Client).handleUnilateral

	github.com/emersion/go-imap/client/_test/_obj_test/client.go:307 +0x112

rax    0xca

rbx    0x0

rcx    0xffffffffffffffff

rdx    0x0

rdi    0x8f2508

rsi    0x0

rbp    0x1

rsp    0x7fff72fc2f10

r8     0x0

r9     0x0

r10    0x0

r11    0x286

r12    0x3

r13    0x7e459e

r14    0x7

r15    0x8

rip    0x460911

rflags 0x286

cs     0x33

fs     0x0

gs     0x0

*** Test killed with quit: ran too long (10m0s).

FAIL	github.com/emersion/go-imap/client	600.005s
```
