### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by beiping96** [emersion/go-imap#327]
``` bash
panic: runtime error: index out of range [1] with length 1

goroutine 1644487 [running]:
github.com/emersion/go-imap/client.(*Client).handleUnilateral.func1(0xce80e0, 0xc001782de0, 0xce8020, 0xc00018c590)
	/home/pp/go/pkg/mod/github.com/emersion/go-imap@v1.0.1/client/client.go:437 +0xcca
github.com/emersion/go-imap/responses.HandlerFunc.Handle(0xc00898d790, 0xce80e0, 0xc001782de0, 0xce8001, 0xc00018c590)
	/home/pp/go/pkg/mod/github.com/emersion/go-imap@v1.0.1/responses/responses.go:27 +0x3a
github.com/emersion/go-imap/client.(*Client).handle(0xc0002af2c0, 0xce80e0, 0xc001782de0, 0x0, 0x0)
	/home/pp/go/pkg/mod/github.com/emersion/go-imap@v1.0.1/client/client.go:119 +0xe4
github.com/emersion/go-imap/client.(*Client).readOnce(0xc0002af2c0, 0xc0039c9201, 0x0, 0x0)
	/home/pp/go/pkg/mod/github.com/emersion/go-imap@v1.0.1/client/client.go:169 +0x18f
github.com/emersion/go-imap/client.(*Client).reader(0xc0002af2c0)
	/home/pp/go/pkg/mod/github.com/emersion/go-imap@v1.0.1/client/client.go:136 +0x6d
created by github.com/emersion/go-imap/client.(*Client).handleGreetAndStartReading
	/home/pp/go/pkg/mod/github.com/emersion/go-imap@v1.0.1/client/client.go:513 +0x16b
```

**Comment by beiping96** [comment]
any `recover()`, please

**Comment by emersion** [comment]
Sounds like `handleUnilateral` is missing bounds checks. No, the correct way to fix this isn't to add `recover`, but to understand why it happens.

Can you `c.SetDebug(os.Stdout)` and copy-paste the result when it crashes, excluding personal information?
