### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by hartshorne** [emersion/go-imap#68]
Since https://github.com/emersion/go-imap/commit/1a174427d0b60d075739f6f23ef2bedff998b662, I am getting occasional (about 70% of the time) panics when reading from a mailbox.

### Code

```go
package main

import (
	"log"
	"os"

	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap/client"
)

func main() {
	log.Println("Connecting to server...")

	// Connect to server
	c, err := client.DialTLS("mail.messagingengine.com:993", nil)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Connected")

	c.SetDebug(os.Stderr)

	// Don't forget to logout
	defer c.Logout()

	// Login
	if err := c.Login("user@fastmail.com", "password"); err != nil {
		log.Fatal(err)
	}
	log.Println("Logged in")

	// List mailboxes
	mailboxes := make(chan *imap.MailboxInfo)
	done := make(chan error, 1)
	go func() {
		done <- c.List("", "*", mailboxes)
	}()

	log.Println("Mailboxes:")
	for m := range mailboxes {
		log.Println("* " + m.Name)
	}

	if err := <-done; err != nil {
		log.Fatal(err)
	}

	// Select INBOX
	mbox, err := c.Select("INBOX", false)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Flags for INBOX:", mbox.Flags)

	seqset, err := imap.NewSeqSet("*:*")
	if err != nil {
		log.Println("Error: %v", err)
	}

	messages := make(chan *imap.Message)
	done = make(chan error, 1)
	go func() {
		done <- c.Fetch(seqset, []string{
			imap.EnvelopeMsgAttr,
		}, messages)
	}()

	for msg := range messages {
		log.Println(msg.Envelope.Subject)
	}

	if err := <-done; err != nil {
		log.Println(err)
	}

	log.Println("Done!")
}
```

### Output

```
2016/10/27 11:43:40 Connecting to server...
2016/10/27 11:43:40 Connected
nSjlRg LOGIN user@fastmail.com password
2016/10/27 11:43:41 Logged in
2016/10/27 11:43:41 Mailboxes:
5Yjc3A LIST "" *
* LIST (\HasChildren) "." INBOX
* LIST (\HasNoChildren \Archive) "." INBOX.Archive
* LIST (\HasNoChildren \Drafts) "." INBOX.Drafts
* LIST (\HasNoChildren) "." INBOX.Marketing
* LIST (\HasNoChildren \Sent) "." INBOX.Sent
* LIST (\HasNoChildren) "." INBOX.Service
* LIST (\HasNoChildren \Junk) "." INBOX.Spam
* LIST (\HasNoChildren \Trash) "." INBOX.Trash
5Yjc3A OK Completed (0.001 secs 14 calls)
2016/10/27 11:43:41 * INBOX
2016/10/27 11:43:41 * INBOX.Archive
2016/10/27 11:43:41 * INBOX.Drafts
2016/10/27 11:43:41 * INBOX.Marketing
2016/10/27 11:43:41 * INBOX.Sent
2016/10/27 11:43:41 * INBOX.Service
2016/10/27 11:43:41 * INBOX.Spam
2016/10/27 11:43:41 * INBOX.Trash
OsES8g SELECT INBOX
* 5 EXISTS
* 0 RECENT
* FLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted)
* OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted \*)] Ok
* OK [UIDVALIDITY 1464806015] Ok
* OK [UIDNEXT 10] Ok
* OK [HIGHESTMODSEQ 65] Ok
* OK [URLMECH INTERNAL] Ok
* OK [ANNOTATIONS 65536] Ok
OsES8g OK [READ-WRITE] Completed
imap/client: 2016/10/27 11:43:41 response has not been handled:  &{* OK HIGHESTMODSEQ [65] Ok}
imap/client: 2016/10/27 11:43:41 response has not been handled:  &{* OK URLMECH [INTERNAL] Ok}
imap/client: 2016/10/27 11:43:41 response has not been handled:  &{* OK ANNOTATIONS [65536] Ok}
2016/10/27 11:43:41 Flags for INBOX: [\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted]
Z1bZWg FETCH * (ENVELOPE)
* 5 FETCH (ENVELOPE ("Mon, 8 Aug 2016 14:34:03 -0700" "Here's a .mov dude" (("Casey Muller" NIL "casey" "bevelmail.com")) (("Casey Muller" NIL "casey" "bevelmail.com")) (("Casey Muller" NIL "casey" "bevelmail.com")) ((NIL NIL "ffbyone" "fastmail.com")) NIL NIL NIL "<CAJkq7gq1RzAUgb0DNWTiB2ZRcSP6GHfyPKXabmsmEddd3mBH-Q@mail.gmail.com>"))
Z1bZWg OK Completed (0.001 sec)
2016/10/27 11:43:41 Done!
panic: send on closed channel

goroutine 25 [running]:
panic(0x1a56c0, 0xc42043cf60)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/emersion/go-imap/responses.(*Fetch).HandleFrom(0xc42041c018, 0xc42040e840, 0x0, 0x0)
	/Users/beau/go/src/github.com/emersion/go-imap/responses/fetch.go:37 +0x37b
github.com/emersion/go-imap/client.(*Client).execute.func2(0xc42040e8a0, 0x29a940, 0xc42041c018, 0xc42041c020)
	/Users/beau/go/src/github.com/emersion/go-imap/client/client.go:128 +0x42
created by github.com/emersion/go-imap/client.(*Client).execute
	/Users/beau/go/src/github.com/emersion/go-imap/client/client.go:134 +0x56a
exit status 2
```

**Comment by emersion** [comment]
Should be fixed now! Sorry about this bug, unit tests didn't caught it because they're too fast.
